#!/bin/bash
if [ ! -f "/etc/update" ];then
cat <<EOF >> /etc/update
2.6
EOF
else
echo " "
fi

grep "2.6" /etc/update >/dev/null

if [ $? -eq 0 ]; then

	echo yes
else
	echo "-------"
 
    wget 
fi

exit 0
