#!/bin/bash
wifiip=$(ip addr |grep inet |grep -v inet6 |grep wlan0|awk '{print $2}' |awk -F "/" '{print $1}')


grep "$wifiip" /var/www/html/ip/index.html >/dev/null

if [ $? -eq 0 ]; then

	echo ip---yes
else
	/usr/local/bin/index.sh

	echo "----开始更换IP------"
fi

exit 0
