#!/bin/sh
### BEGIN INIT INFO
# Provides:          qbittorrent-nox
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: qbittorrent-nox
# Description:       qbittorrent-nox
# Author:            Cedric Quillevere / origin@killy.net
# Rewamped	     Christian Svedin / christian.svedin@gmail.com
# Version:           1.2
### END INIT INFO
de=$(ps -ef |grep deluge-we |grep -v "grep" |wc -l)
sync=$(ps -ef |grep rslsync |grep -v "grep" |wc -l)
aria=$(ps -ef |grep aria2c |grep -v "grep" |wc -l)
baidu=$(ps -ef |grep BaiduPCS-Go |grep -v "grep" |wc -l)
netsa=$(ps -ef |grep netdata |grep -v "grep" |wc -l)
apache=$(ps -ef |grep apache2 |grep -v "grep" |wc -l)
smb=$(ps -ef |grep  smbd |grep -v "grep" |wc -l)
webssh=$(ps -ef |grep perl |grep -v "grep" |wc -l)
plex=$(ps -ef |grep Plex |grep -v "grep" |wc -l)

case "$1" in
start)

for stat in {1..3}

do

###############################################
if [ $apache -eq 0 ]; then
   service apache2 restart >/dev/null 2>&1
   echo "正在启动apache2"
   
else
    echo "阿帕奇正在运行"
fi
#############################################

  if [ $smb -eq 0 ]; then
    service smbd start >/dev/null 2>&1
    echo "正在启动smb"
   
else
    echo "局域网共享正在运行"
fi  
#########################################

  if [ $webssh -eq 0 ]; then
     service webmin restart >/dev/null 2>&1
     echo "正在启动webmin"
else
    echo "WEBssh正在运行"
fi 
###################################
 if [ $plex -eq 0 ]; then
   service plexmediaserver start >/dev/null 2>&1

   echo "正在启动PLEX"
   
else
    echo "PLEX正在运行"
fi 

#############################
if [ $sync -eq 0 ]; then
     rslsync  --config /opt/sync.conf  >/dev/null 2>&1
     echo "正在启动rslsync"
else
        echo sync正在运行
fi
#################################
if [ $aria -eq 0 ]; then
       sudo aria2c --conf-path=/etc/aria2/aria2.conf -D&
       echo "正在启动aria2"
else
        echo aria2正在运行
fi
################################
if [ $baidu -eq 0 ]; then
        BaiduPCS-Go  >/dev/null &
        echo "正在启动BaiduPCS-Go"
else
        echo BaiduPCS正在运行
fi
#####################################
if [ $netsa -eq 0 ]; then
        nohup sudo  netdata >/dev/null  2>&1
        echo "正在启动netdata"
else
        echo "资源检测正在运行"
fi
########################################
if [ $de -eq 0 ]; then
   deluged  >/dev/null  2>&1
  nohup deluge-web  >/dev/null &
   echo "正在启动deluge-web"
   
else
        echo BT正在运行
fi
echo "--------------------------------------------------------"
###############################

done

;;
stop)
  
 echo "没有命令"
;;
restart)
 echo "没有命令"
esac
exit 0
